name: Website
on:
  push:
    branches: [main, master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: olafurpg/setup-scala@v13

      - name: Install SSH deploy key
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${GIT_DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - run: sbt '++2.13.15 docusaurusPublishGhpages'

      - name: Check git diff
        if: ${{ failure() }}
        run: git diff
