name: docs-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"

      - name: Install SSH deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Publish Docusaurus to gh‑pages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: sbt '++2.13.15 docusaurusPublishGhpages'
