name: Website
on:
  push:
    branches: [main, master]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: olafurpg/setup-scala@v13

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GIT_DEPLOY_KEY }}

      - name: Publish Docusaurus to gh-pages
        run: sbt '++2.13.15 docusaurusPublishGhpages'

      - name: Check git diff if deploy failed
        if: ${{ failure() }}
        run: git diff
