name: Website
on:
  push:
    branches: [main, master]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13

      - name: Decode & install SSH key
        env:
          SSH_KEY_B64: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY_B64" \
            | base64 --decode \
            | tr -d '\r' \
            > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Configure git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Publish Docusaurus to gh-pages
        run: sbt '++2.13.15 docusaurusPublishGhpages'

      - name: Show diff on failure
        if: ${{ failure() }}
        run: git diff
